const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    //user
    ADD_NEW_ACCOUNT_SUCCESS: 'ADD_NEW_ACCOUNT_SUCCESS',
    ADD_NEW_ACCOUNT_FAIL: 'ADD_NEW_ACCOUNT_FAIL',

    ADD_NEW_PRODUCT_SUCCESS: 'ADD_NEW_PRODUCT_SUCCESS',
    ADD_NEW_PRODUCT_FAIL: 'ADD_NEW_PRODUCT_FAIL',

    FETCH_PRODUCT_LIST_SUCCESS: 'FETCH_PRODUCT_LIST_SUCCESS',
    FETCH_PRODUCT_LIST_FAIL: 'FETCH_PRODUCT_LIST_FAIL',

    FETCH_STOCK_LIST_SUCCESS: 'FETCH_STOCK_LIST_SUCCESS',
    FETCH_STOCK_LIST_FAIL: 'FETCH_STOCK_LIST_FAIL',
    FETCH_PRODUCT_IN_STOCK_SUCCESS: 'FETCH_PRODUCT_IN_STOCK_SUCCESS',
    FETCH_PRODUCT_IN_STOCK_FAIL: 'FETCH_PRODUCT_IN_STOCK_FAIL',

    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
})

export default actionTypes;